# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OnInkMainWindow(object):
    def setupUi(self, OnInkMainWindow):
        OnInkMainWindow.setObjectName("OnInkMainWindow")
        OnInkMainWindow.resize(900, 700)
        OnInkMainWindow.setMinimumSize(QtCore.QSize(900, 700))
        OnInkMainWindow.setStyleSheet("@font-face{\n"
" font-family: \"Oswald\";\n"
" src: url(\"/fonts/Oswald/Oswald-VariableFont_wght.ttf\");\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=OnInkMainWindow)
        self.centralwidget.setStyleSheet("QLabel{\n"
" font-family: \"Oswald\";\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(44, 62, 80);\n"
"font-family: \"Oswald\";\n"
"\n"
"QMenu{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color: rgb(44, 62, 80);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(128, 128, 128);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-size:16pt;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"QMenu{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_menu = QtWidgets.QPushButton(parent=self.frame_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_menu.sizePolicy().hasHeightForWidth())
        self.bt_menu.setSizePolicy(sizePolicy)
        self.bt_menu.setMinimumSize(QtCore.QSize(200, 65))
        self.bt_menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu.setWhatsThis("")
        self.bt_menu.setAccessibleDescription("")
        self.bt_menu.setStyleSheet("QPushButton{\n"
"    border-radius:0px;\n"
"    background-color: rgb(44, 62, 80);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(128, 128, 128);\n"
"}\n"
"")
        self.bt_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/sidebar-menu.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu.setIcon(icon)
        self.bt_menu.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout.addWidget(self.bt_menu)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame_superior)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(199, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/minimize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_minimizar.setIcon(icon1)
        self.bt_minimizar.setIconSize(QtCore.QSize(32, 32))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_restaurar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/restaurar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_restaurar.setIcon(icon2)
        self.bt_restaurar.setIconSize(QtCore.QSize(32, 32))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_maximizar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/maximize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_maximizar.setIcon(icon3)
        self.bt_maximizar.setIconSize(QtCore.QSize(32, 32))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_close = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_close.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_close.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_close.setIcon(icon4)
        self.bt_close.setIconSize(QtCore.QSize(32, 32))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout.addWidget(self.bt_close)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(parent=self.frame)
        self.frame_contenido.setStyleSheet("QMenu{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QMenu::item:disabled{\n"
"    \n"
"    color: rgb(166, 166, 166);\n"
"}\n"
"QMenu::item:enabled:selected{\n"
"    background-color: rgb(47, 28, 255);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_control = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_control.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_control.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_control.setStyleSheet("")
        self.frame_control.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_control.setObjectName("frame_control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_control)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_control)
        self.scrollArea.setStyleSheet("QWidget{\n"
"border: none;\n"
"    \n"
"    background-color: rgb(128, 128, 128);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(128, 128, 0);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    font-family:\"Oswald\";\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,255,255);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"QScrollArea {\n"
"        border-radius: 5px;\n"
"        margin: 5px;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: rgb(235, 235, 235);\n"
"        width: 10px;\n"
"        margin: 0px 0 0px 0;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"    background-color: rgb(243, 156, 18);\n"
"        min-height: 20px;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        background-color: #F5F5F5;\n"
"        height: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"        border-top-left-radius: 5px;\n"
"        border-top-right-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        background-color: #F5F5F5;\n"
"        height: 0px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"        border-bottom-left-radius: 5px;\n"
"        border-bottom-right-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background-color: none;\n"
"    }\n"
"\n"
"    ")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget_menu_lateral = QtWidgets.QWidget()
        self.widget_menu_lateral.setGeometry(QtCore.QRect(0, 0, 171, 1392))
        self.widget_menu_lateral.setObjectName("widget_menu_lateral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_menu_lateral)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_menu_lateral)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setStyleSheet("font-weight: bold;\n"
"font-size: 12pt;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.bt_menu_clientes = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_clientes.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_clientes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_clientes.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/user.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_clientes.setIcon(icon5)
        self.bt_menu_clientes.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_clientes.setObjectName("bt_menu_clientes")
        self.verticalLayout_4.addWidget(self.bt_menu_clientes)
        self.bt_redes_sociales_28 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_28.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_28.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_28.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/social-network.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_28.setIcon(icon6)
        self.bt_redes_sociales_28.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_28.setObjectName("bt_redes_sociales_28")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_28)
        self.bt_redes_sociales_27 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_27.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_27.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_27.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/services-portfolio.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_27.setIcon(icon7)
        self.bt_redes_sociales_27.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_27.setObjectName("bt_redes_sociales_27")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_27)
        self.bt_redes_sociales_26 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_26.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_26.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_26.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/country-2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_26.setIcon(icon8)
        self.bt_redes_sociales_26.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_26.setObjectName("bt_redes_sociales_26")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_26)
        self.bt_redes_sociales_25 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_25.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_25.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_25.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/flag-1.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_25.setIcon(icon9)
        self.bt_redes_sociales_25.setIconSize(QtCore.QSize(30, 30))
        self.bt_redes_sociales_25.setObjectName("bt_redes_sociales_25")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_25)
        self.bt_redes_sociales_24 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_24.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_24.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_24.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/location.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_24.setIcon(icon10)
        self.bt_redes_sociales_24.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_24.setObjectName("bt_redes_sociales_24")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_24)
        self.bt_redes_sociales_23 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_23.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_23.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_23.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/materials.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_23.setIcon(icon11)
        self.bt_redes_sociales_23.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_23.setObjectName("bt_redes_sociales_23")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_23)
        self.bt_redes_sociales_22 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_22.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_22.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_22.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/solution.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_22.setIcon(icon12)
        self.bt_redes_sociales_22.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_22.setObjectName("bt_redes_sociales_22")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_22)
        self.bt_redes_sociales_21 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_21.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_21.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_21.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/palette.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_21.setIcon(icon13)
        self.bt_redes_sociales_21.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_21.setObjectName("bt_redes_sociales_21")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_21)
        self.bt_redes_sociales_20 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_20.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_20.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_20.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/credit-card.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_redes_sociales_20.setIcon(icon14)
        self.bt_redes_sociales_20.setIconSize(QtCore.QSize(35, 35))
        self.bt_redes_sociales_20.setObjectName("bt_redes_sociales_20")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_20)
        self.bt_redes_sociales_19 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_19.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_19.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_19.setObjectName("bt_redes_sociales_19")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_19)
        self.bt_redes_sociales_18 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_18.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_18.setObjectName("bt_redes_sociales_18")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_18)
        self.bt_redes_sociales_17 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_17.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_17.setObjectName("bt_redes_sociales_17")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_17)
        self.bt_redes_sociales_16 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_16.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_16.setObjectName("bt_redes_sociales_16")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_16)
        self.bt_redes_sociales_15 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_15.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_15.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_15.setObjectName("bt_redes_sociales_15")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_15)
        self.bt_redes_sociales_14 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_14.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_14.setObjectName("bt_redes_sociales_14")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_14)
        self.bt_redes_sociales_13 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_13.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_13.setObjectName("bt_redes_sociales_13")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_13)
        self.bt_redes_sociales_12 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_12.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_12.setObjectName("bt_redes_sociales_12")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_12)
        self.bt_redes_sociales_11 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_11.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_11.setObjectName("bt_redes_sociales_11")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_11)
        self.bt_redes_sociales_10 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_10.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_10.setObjectName("bt_redes_sociales_10")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_10)
        self.bt_redes_sociales_9 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_9.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_9.setObjectName("bt_redes_sociales_9")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_9)
        self.bt_redes_sociales_8 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_8.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_8.setObjectName("bt_redes_sociales_8")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_8)
        self.bt_redes_sociales_7 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_7.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_7.setObjectName("bt_redes_sociales_7")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_7)
        self.bt_redes_sociales_6 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_6.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_6.setObjectName("bt_redes_sociales_6")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_6)
        self.bt_redes_sociales_5 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_5.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_5.setObjectName("bt_redes_sociales_5")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_5)
        self.bt_redes_sociales_4 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_4.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_4.setObjectName("bt_redes_sociales_4")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_4)
        self.bt_redes_sociales_3 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_3.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_3.setObjectName("bt_redes_sociales_3")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_3)
        self.bt_redes_sociales_2 = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales_2.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales_2.setObjectName("bt_redes_sociales_2")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales_2)
        self.bt_redes_sociales = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_redes_sociales.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_redes_sociales.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_redes_sociales.setObjectName("bt_redes_sociales")
        self.verticalLayout_4.addWidget(self.bt_redes_sociales)
        self.scrollArea.setWidget(self.widget_menu_lateral)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.frame_control)
        self.frame_paginas = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_paginas)
        self.stackedWidget.setStyleSheet("QLabel{\n"
"font-family:\"Oswald\";\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(180, 180, 180);\n"
"    border: 3px solid   rgb(50, 50, 50);\n"
"    padding: 5px;\n"
"    border-radius:10px;\n"
"font-family:\"Oswald\";\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(244, 240, 240);\n"
"    \n"
"}\n"
"\n"
" QLineEdit {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-family: \"Oswald\";\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border: 2px solid rgb(255, 140, 0);\n"
"    }\n"
"QComboBox {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-family: \"Oswald\";\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QComboBox::drop-down {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 20px;\n"
"        border-left-width: 0px;\n"
"        border-top-right-radius: 10px;\n"
"        border-bottom-right-radius: 10px;\n"
"        background-color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"    QComboBox::down-arrow {\n"
"        image: url(\"images/dropdownbtn.png\");\n"
"        width: 20px;\n"
"        height: 20px;\n"
"    }\n"
"\n"
"   QComboBox:focus {\n"
"        border: 2px solid rgb(255, 255, 255);\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: rgb(21, 128, 194);\n"
"        color: white;\n"
"        selection-background-color: rgb(255, 255, 255);\n"
"        selection-color: black;\n"
"    }\n"
"QTextEdit {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"    QTextEdit:focus {\n"
"         border: 2px solid rgb(255, 140, 0);\n"
"    }")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_inicio = QtWidgets.QWidget()
        self.page_inicio.setObjectName("page_inicio")
        self.stackedWidget.addWidget(self.page_inicio)
        self.page_clientes = QtWidgets.QWidget()
        self.page_clientes.setObjectName("page_clientes")
        self.verticalLayout_page_clientes = QtWidgets.QVBoxLayout(self.page_clientes)
        self.verticalLayout_page_clientes.setObjectName("verticalLayout_page_clientes")
        self.verticalLayout_search_clientes = QtWidgets.QVBoxLayout()
        self.verticalLayout_search_clientes.setObjectName("verticalLayout_search_clientes")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(parent=self.page_clientes)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-size: 16pt;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.bt_create_cliente = QtWidgets.QPushButton(parent=self.page_clientes)
        self.bt_create_cliente.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/add-client.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_create_cliente.setIcon(icon15)
        self.bt_create_cliente.setIconSize(QtCore.QSize(25, 25))
        self.bt_create_cliente.setObjectName("bt_create_cliente")
        self.horizontalLayout_3.addWidget(self.bt_create_cliente)
        self.verticalLayout_search_clientes.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(parent=self.page_clientes)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.le_search_clients = QtWidgets.QLineEdit(parent=self.page_clientes)
        self.le_search_clients.setObjectName("le_search_clients")
        self.horizontalLayout_15.addWidget(self.le_search_clients)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.bt_refresh_search_clients = QtWidgets.QPushButton(parent=self.page_clientes)
        self.bt_refresh_search_clients.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/refresh.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_refresh_search_clients.setIcon(icon16)
        self.bt_refresh_search_clients.setIconSize(QtCore.QSize(32, 32))
        self.bt_refresh_search_clients.setObjectName("bt_refresh_search_clients")
        self.horizontalLayout_15.addWidget(self.bt_refresh_search_clients)
        self.verticalLayout_search_clientes.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(11)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(parent=self.page_clientes)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.cb_search_clientes_pais = QtWidgets.QComboBox(parent=self.page_clientes)
        self.cb_search_clientes_pais.setObjectName("cb_search_clientes_pais")
        self.horizontalLayout_16.addWidget(self.cb_search_clientes_pais)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(parent=self.page_clientes)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.cb_search_clientes_provincia = QtWidgets.QComboBox(parent=self.page_clientes)
        self.cb_search_clientes_provincia.setObjectName("cb_search_clientes_provincia")
        self.horizontalLayout_17.addWidget(self.cb_search_clientes_provincia)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.label_18 = QtWidgets.QLabel(parent=self.page_clientes)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.cb_search_clientes_municipio = QtWidgets.QComboBox(parent=self.page_clientes)
        self.cb_search_clientes_municipio.setObjectName("cb_search_clientes_municipio")
        self.horizontalLayout_18.addWidget(self.cb_search_clientes_municipio)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_18)
        self.verticalLayout_search_clientes.addLayout(self.horizontalLayout_19)
        self.verticalLayout_page_clientes.addLayout(self.verticalLayout_search_clientes)
        self.stackedWidget.addWidget(self.page_clientes)
        self.page_insertar_cliente = QtWidgets.QWidget()
        self.page_insertar_cliente.setObjectName("page_insertar_cliente")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_insertar_cliente)
        self.verticalLayout_9.setSpacing(9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_volver_cliente_c = QtWidgets.QPushButton(parent=self.page_insertar_cliente)
        self.bt_volver_cliente_c.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/back-arrow.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_volver_cliente_c.setIcon(icon17)
        self.bt_volver_cliente_c.setIconSize(QtCore.QSize(25, 25))
        self.bt_volver_cliente_c.setObjectName("bt_volver_cliente_c")
        self.horizontalLayout_4.addWidget(self.bt_volver_cliente_c)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label_4 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_4.setStyleSheet("font-size: 16pt;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 3)
        self.horizontalLayout_4.setStretch(3, 3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lb_pic_insert_cliente = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.lb_pic_insert_cliente.setMinimumSize(QtCore.QSize(230, 230))
        self.lb_pic_insert_cliente.setStyleSheet("border: 3px solid white")
        self.lb_pic_insert_cliente.setText("")
        self.lb_pic_insert_cliente.setPixmap(QtGui.QPixmap("C:/Users/Jose/.designer/backup/clients_pictures/00000000000.png"))
        self.lb_pic_insert_cliente.setScaledContents(True)
        self.lb_pic_insert_cliente.setObjectName("lb_pic_insert_cliente")
        self.horizontalLayout_12.addWidget(self.lb_pic_insert_cliente)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bt_add_image_clients_insert = QtWidgets.QPushButton(parent=self.page_insertar_cliente)
        self.bt_add_image_clients_insert.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/upload-picture.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_add_image_clients_insert.setIcon(icon18)
        self.bt_add_image_clients_insert.setIconSize(QtCore.QSize(32, 32))
        self.bt_add_image_clients_insert.setObjectName("bt_add_image_clients_insert")
        self.verticalLayout_6.addWidget(self.bt_add_image_clients_insert)
        self.bt_delete_image_clients_insert = QtWidgets.QPushButton(parent=self.page_insertar_cliente)
        self.bt_delete_image_clients_insert.setText("")
        self.bt_delete_image_clients_insert.setIcon(icon16)
        self.bt_delete_image_clients_insert.setIconSize(QtCore.QSize(32, 32))
        self.bt_delete_image_clients_insert.setObjectName("bt_delete_image_clients_insert")
        self.verticalLayout_6.addWidget(self.bt_delete_image_clients_insert)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.le_ci_insertar = QtWidgets.QLineEdit(parent=self.page_insertar_cliente)
        self.le_ci_insertar.setInputMask("")
        self.le_ci_insertar.setText("")
        self.le_ci_insertar.setMaxLength(11)
        self.le_ci_insertar.setObjectName("le_ci_insertar")
        self.horizontalLayout_5.addWidget(self.le_ci_insertar)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.le_telefono_insertar = QtWidgets.QLineEdit(parent=self.page_insertar_cliente)
        self.le_telefono_insertar.setObjectName("le_telefono_insertar")
        self.horizontalLayout_11.addWidget(self.le_telefono_insertar)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.le_nombre_apellidos_insertar = QtWidgets.QLineEdit(parent=self.page_insertar_cliente)
        self.le_nombre_apellidos_insertar.setObjectName("le_nombre_apellidos_insertar")
        self.horizontalLayout_6.addWidget(self.le_nombre_apellidos_insertar)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.cb_pais_insertar = QtWidgets.QComboBox(parent=self.page_insertar_cliente)
        self.cb_pais_insertar.setObjectName("cb_pais_insertar")
        self.horizontalLayout_7.addWidget(self.cb_pais_insertar)
        self.label_9 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.cb_provincia_insertar = QtWidgets.QComboBox(parent=self.page_insertar_cliente)
        self.cb_provincia_insertar.setObjectName("cb_provincia_insertar")
        self.horizontalLayout_7.addWidget(self.cb_provincia_insertar)
        self.label_10 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.cb_municipio_insertar = QtWidgets.QComboBox(parent=self.page_insertar_cliente)
        self.cb_municipio_insertar.setObjectName("cb_municipio_insertar")
        self.horizontalLayout_7.addWidget(self.cb_municipio_insertar)
        self.horizontalLayout_7.setStretch(1, 3)
        self.horizontalLayout_7.setStretch(3, 3)
        self.horizontalLayout_7.setStretch(5, 3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.txtedt_notas_insertar = QtWidgets.QTextEdit(parent=self.page_insertar_cliente)
        self.txtedt_notas_insertar.setMinimumSize(QtCore.QSize(0, 30))
        self.txtedt_notas_insertar.setObjectName("txtedt_notas_insertar")
        self.horizontalLayout_9.addWidget(self.txtedt_notas_insertar)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(parent=self.page_insertar_cliente)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.txedt_alcance = QtWidgets.QTextEdit(parent=self.page_insertar_cliente)
        self.txedt_alcance.setMinimumSize(QtCore.QSize(0, 30))
        self.txedt_alcance.setObjectName("txedt_alcance")
        self.horizontalLayout_8.addWidget(self.txedt_alcance)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bt_cliente_insertar_reestablecer = QtWidgets.QPushButton(parent=self.page_insertar_cliente)
        self.bt_cliente_insertar_reestablecer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_cliente_insertar_reestablecer.setIcon(icon16)
        self.bt_cliente_insertar_reestablecer.setIconSize(QtCore.QSize(25, 25))
        self.bt_cliente_insertar_reestablecer.setObjectName("bt_cliente_insertar_reestablecer")
        self.horizontalLayout_10.addWidget(self.bt_cliente_insertar_reestablecer)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.bt_store_cliente = QtWidgets.QPushButton(parent=self.page_insertar_cliente)
        self.bt_store_cliente.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\images/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_store_cliente.setIcon(icon19)
        self.bt_store_cliente.setIconSize(QtCore.QSize(25, 25))
        self.bt_store_cliente.setObjectName("bt_store_cliente")
        self.horizontalLayout_10.addWidget(self.bt_store_cliente)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.page_insertar_cliente)
        self.page_add_social_usernames = QtWidgets.QWidget()
        self.page_add_social_usernames.setObjectName("page_add_social_usernames")
        self.verticalLayout_usernames = QtWidgets.QVBoxLayout(self.page_add_social_usernames)
        self.verticalLayout_usernames.setObjectName("verticalLayout_usernames")
        self.label_13 = QtWidgets.QLabel(parent=self.page_add_social_usernames)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font-size: 16pt;")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_usernames.addWidget(self.label_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lb_cliente_name = QtWidgets.QLabel(parent=self.page_add_social_usernames)
        self.lb_cliente_name.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lb_cliente_name.setObjectName("lb_cliente_name")
        self.horizontalLayout_14.addWidget(self.lb_cliente_name)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.bt_save_usernames = QtWidgets.QPushButton(parent=self.page_add_social_usernames)
        self.bt_save_usernames.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_save_usernames.setIcon(icon19)
        self.bt_save_usernames.setIconSize(QtCore.QSize(32, 32))
        self.bt_save_usernames.setObjectName("bt_save_usernames")
        self.horizontalLayout_14.addWidget(self.bt_save_usernames)
        self.verticalLayout_usernames.addLayout(self.horizontalLayout_14)
        self.verticalLySocials = QtWidgets.QVBoxLayout()
        self.verticalLySocials.setObjectName("verticalLySocials")
        self.verticalLayout_usernames.addLayout(self.verticalLySocials)
        spacerItem17 = QtWidgets.QSpacerItem(20, 495, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_usernames.addItem(spacerItem17)
        self.stackedWidget.addWidget(self.page_add_social_usernames)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_paginas)
        self.verticalLayout_2.addWidget(self.frame_contenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        OnInkMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OnInkMainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.bt_close.clicked.connect(OnInkMainWindow.close) # type: ignore
        self.bt_maximizar.clicked.connect(OnInkMainWindow.showMaximized) # type: ignore
        self.bt_maximizar.clicked.connect(self.bt_restaurar.show) # type: ignore
        self.bt_maximizar.clicked.connect(self.bt_maximizar.hide) # type: ignore
        self.bt_minimizar.clicked.connect(OnInkMainWindow.showMinimized) # type: ignore
        self.bt_restaurar.clicked.connect(self.bt_maximizar.show) # type: ignore
        self.bt_restaurar.clicked.connect(self.bt_restaurar.hide) # type: ignore
        self.bt_restaurar.clicked.connect(OnInkMainWindow.showNormal) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OnInkMainWindow)

    def retranslateUi(self, OnInkMainWindow):
        _translate = QtCore.QCoreApplication.translate
        OnInkMainWindow.setWindowTitle(_translate("OnInkMainWindow", "MainWindow"))
        self.bt_menu.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#040404;\">Mostrar/Ocultar menú</span></p></body></html>"))
        self.label.setText(_translate("OnInkMainWindow", "OnInk"))
        self.bt_minimizar.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Minimizar</span></p></body></html>"))
        self.bt_restaurar.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Normal</span></p></body></html>"))
        self.bt_maximizar.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Maximizar</span></p></body></html>"))
        self.bt_close.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Cerrar</span></p></body></html>"))
        self.label_2.setText(_translate("OnInkMainWindow", "Menú de opciones"))
        self.bt_menu_clientes.setText(_translate("OnInkMainWindow", "Clientes"))
        self.bt_redes_sociales_28.setText(_translate("OnInkMainWindow", "Redes"))
        self.bt_redes_sociales_27.setText(_translate("OnInkMainWindow", "Trabajos"))
        self.bt_redes_sociales_26.setText(_translate("OnInkMainWindow", "Países"))
        self.bt_redes_sociales_25.setText(_translate("OnInkMainWindow", "Provincias"))
        self.bt_redes_sociales_24.setText(_translate("OnInkMainWindow", "Municipios"))
        self.bt_redes_sociales_23.setText(_translate("OnInkMainWindow", "Materiales"))
        self.bt_redes_sociales_22.setText(_translate("OnInkMainWindow", "Técnicas"))
        self.bt_redes_sociales_21.setText(_translate("OnInkMainWindow", "Tonos"))
        self.bt_redes_sociales_20.setText(_translate("OnInkMainWindow", "Pagos"))
        self.bt_redes_sociales_19.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_18.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_17.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_16.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_15.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_14.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_13.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_12.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_11.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_10.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_9.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_8.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_7.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_6.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_5.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_4.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_3.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales_2.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.bt_redes_sociales.setText(_translate("OnInkMainWindow", "Redes Sociales"))
        self.label_3.setText(_translate("OnInkMainWindow", "Gestión de clientes"))
        self.bt_create_cliente.setText(_translate("OnInkMainWindow", "Agregar nuevo"))
        self.label_14.setText(_translate("OnInkMainWindow", "Buscar: "))
        self.le_search_clients.setPlaceholderText(_translate("OnInkMainWindow", "Buscar..."))
        self.bt_refresh_search_clients.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p>Reiniciar filtros de búsqueda</p></body></html>"))
        self.label_15.setText(_translate("OnInkMainWindow", "Pais: "))
        self.cb_search_clientes_pais.setPlaceholderText(_translate("OnInkMainWindow", "País..."))
        self.label_16.setText(_translate("OnInkMainWindow", "Provincia: "))
        self.cb_search_clientes_provincia.setPlaceholderText(_translate("OnInkMainWindow", "Provincia..."))
        self.label_18.setText(_translate("OnInkMainWindow", "Municipio: "))
        self.cb_search_clientes_municipio.setPlaceholderText(_translate("OnInkMainWindow", "Municipio"))
        self.bt_volver_cliente_c.setText(_translate("OnInkMainWindow", "Volver"))
        self.label_4.setText(_translate("OnInkMainWindow", "Insertar datos del cliente"))
        self.bt_add_image_clients_insert.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p>Añadir imagen</p></body></html>"))
        self.bt_delete_image_clients_insert.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p>Reestablecer imagen</p></body></html>"))
        self.label_5.setText(_translate("OnInkMainWindow", "CI: "))
        self.le_ci_insertar.setPlaceholderText(_translate("OnInkMainWindow", "Número de identidad"))
        self.label_7.setText(_translate("OnInkMainWindow", "Teléfono: "))
        self.le_telefono_insertar.setPlaceholderText(_translate("OnInkMainWindow", "Número de teléfono"))
        self.label_6.setText(_translate("OnInkMainWindow", "Nombre y apellidos: "))
        self.le_nombre_apellidos_insertar.setPlaceholderText(_translate("OnInkMainWindow", "Nombre y apellidos"))
        self.label_8.setText(_translate("OnInkMainWindow", "País: "))
        self.cb_pais_insertar.setPlaceholderText(_translate("OnInkMainWindow", "Seleccionar País"))
        self.label_9.setText(_translate("OnInkMainWindow", "Provincia:"))
        self.cb_provincia_insertar.setPlaceholderText(_translate("OnInkMainWindow", "Seleccionar provincia"))
        self.label_10.setText(_translate("OnInkMainWindow", "Municipio:"))
        self.cb_municipio_insertar.setPlaceholderText(_translate("OnInkMainWindow", "Seleccionar municipio"))
        self.label_11.setText(_translate("OnInkMainWindow", "Notas:"))
        self.txtedt_notas_insertar.setPlaceholderText(_translate("OnInkMainWindow", "Notas acerca del cliente"))
        self.label_12.setText(_translate("OnInkMainWindow", "Vía de llegada:"))
        self.txedt_alcance.setPlaceholderText(_translate("OnInkMainWindow", "Vía por la que llegó"))
        self.bt_cliente_insertar_reestablecer.setText(_translate("OnInkMainWindow", "Reestablecer"))
        self.bt_store_cliente.setText(_translate("OnInkMainWindow", "Agregar"))
        self.label_13.setText(_translate("OnInkMainWindow", "Redes sociales del cliente"))
        self.lb_cliente_name.setText(_translate("OnInkMainWindow", "Cliente: "))
        self.bt_save_usernames.setText(_translate("OnInkMainWindow", "Guardar"))
