# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\views\createSocial.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_socialCreate(object):
    def setupUi(self, socialCreate):
        socialCreate.setObjectName("socialCreate")
        socialCreate.resize(660, 512)
        self.verticalLayout = QtWidgets.QVBoxLayout(socialCreate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_back = QtWidgets.QPushButton(parent=socialCreate)
        self.bt_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/back-arrow.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_back.setIcon(icon)
        self.bt_back.setIconSize(QtCore.QSize(32, 32))
        self.bt_back.setObjectName("bt_back")
        self.horizontalLayout.addWidget(self.bt_back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(parent=socialCreate)
        self.pushButton.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/social-network - white.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=socialCreate)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.social = QtWidgets.QLineEdit(parent=socialCreate)
        self.social.setObjectName("social")
        self.horizontalLayout_2.addWidget(self.social)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 259, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bt_save = QtWidgets.QPushButton(parent=socialCreate)
        self.bt_save.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_save.setIcon(icon2)
        self.bt_save.setIconSize(QtCore.QSize(32, 32))
        self.bt_save.setObjectName("bt_save")
        self.horizontalLayout_3.addWidget(self.bt_save)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(socialCreate)
        QtCore.QMetaObject.connectSlotsByName(socialCreate)

    def retranslateUi(self, socialCreate):
        _translate = QtCore.QCoreApplication.translate
        socialCreate.setWindowTitle(_translate("socialCreate", "Form"))
        self.bt_back.setText(_translate("socialCreate", "Volver"))
        self.label.setText(_translate("socialCreate", "Red social: "))
        self.social.setPlaceholderText(_translate("socialCreate", "Nombre de red social"))
        self.bt_save.setText(_translate("socialCreate", "Guardar"))
