# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\views\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OnInkMainWindow(object):
    def setupUi(self, OnInkMainWindow):
        OnInkMainWindow.setObjectName("OnInkMainWindow")
        OnInkMainWindow.resize(900, 700)
        OnInkMainWindow.setMinimumSize(QtCore.QSize(900, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        OnInkMainWindow.setWindowIcon(icon)
        OnInkMainWindow.setStyleSheet("@font-face{\n"
" font-family: \"Oswald\";\n"
" src: url(\"/fonts/Oswald/Oswald-VariableFont_wght.ttf\");\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=OnInkMainWindow)
        self.centralwidget.setStyleSheet("QLabel{\n"
" font-family: \"Oswald\";\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(44, 62, 80);\n"
"}\n"
"font-family: \"Oswald\";\n"
"QMenu{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color: rgb(44, 62, 80);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(128, 128, 128);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"    font-size:16pt;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"QMenu{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_menu = QtWidgets.QPushButton(parent=self.frame_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_menu.sizePolicy().hasHeightForWidth())
        self.bt_menu.setSizePolicy(sizePolicy)
        self.bt_menu.setMinimumSize(QtCore.QSize(200, 65))
        self.bt_menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu.setWhatsThis("")
        self.bt_menu.setAccessibleDescription("")
        self.bt_menu.setStyleSheet("QPushButton{\n"
"    border-radius:0px;\n"
"    background-color: rgb(44, 62, 80);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(128, 128, 128);\n"
"}\n"
"")
        self.bt_menu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/sidebar-menu.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu.setIcon(icon1)
        self.bt_menu.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout.addWidget(self.bt_menu)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame_superior)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(199, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_minimizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/minimize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_minimizar.setIcon(icon2)
        self.bt_minimizar.setIconSize(QtCore.QSize(32, 32))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_restaurar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/restaurar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_restaurar.setIcon(icon3)
        self.bt_restaurar.setIconSize(QtCore.QSize(32, 32))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_maximizar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/maximize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_maximizar.setIcon(icon4)
        self.bt_maximizar.setIconSize(QtCore.QSize(32, 32))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_close = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_close.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_close.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_close.setIcon(icon5)
        self.bt_close.setIconSize(QtCore.QSize(32, 32))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout.addWidget(self.bt_close)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(parent=self.frame)
        self.frame_contenido.setStyleSheet("QMenu{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QMenu::item:disabled{\n"
"    \n"
"    color: rgb(166, 166, 166);\n"
"}\n"
"QMenu::item:enabled:selected{\n"
"    background-color: rgb(47, 28, 255);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
" ")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_control = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_control.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_control.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_control.setStyleSheet("")
        self.frame_control.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_control.setObjectName("frame_control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_control)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_control)
        self.scrollArea.setStyleSheet("QWidget{\n"
"border: none;\n"
"    \n"
"    background-color: rgb(128, 128, 128);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(128, 128, 0);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    font-family:\"Oswald\";\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,255,255);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"QScrollArea {\n"
"        border-radius: 5px;\n"
"        margin: 5px;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: rgb(235, 235, 235);\n"
"        width: 10px;\n"
"        margin: 0px 0 0px 0;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"    background-color: rgb(243, 156, 18);\n"
"        min-height: 20px;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        background-color: #F5F5F5;\n"
"        height: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"        border-top-left-radius: 5px;\n"
"        border-top-right-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        background-color: #F5F5F5;\n"
"        height: 0px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"        border-bottom-left-radius: 5px;\n"
"        border-bottom-right-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background-color: none;\n"
"    }\n"
"\n"
"    ")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget_menu_lateral = QtWidgets.QWidget()
        self.widget_menu_lateral.setGeometry(QtCore.QRect(0, 0, 178, 656))
        self.widget_menu_lateral.setObjectName("widget_menu_lateral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_menu_lateral)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_menu_lateral)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setStyleSheet("font-weight: bold;\n"
"font-size: 12pt;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.bt_menu_home = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_home.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_home.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/home (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_home.setIcon(icon6)
        self.bt_menu_home.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_home.setObjectName("bt_menu_home")
        self.verticalLayout_4.addWidget(self.bt_menu_home)
        self.bt_menu_clientes = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_clientes.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_clientes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_clientes.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/user.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_clientes.setIcon(icon7)
        self.bt_menu_clientes.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_clientes.setObjectName("bt_menu_clientes")
        self.verticalLayout_4.addWidget(self.bt_menu_clientes)
        self.bt_menu_trabajos = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_trabajos.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_trabajos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_trabajos.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/services-portfolio.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_trabajos.setIcon(icon8)
        self.bt_menu_trabajos.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_trabajos.setObjectName("bt_menu_trabajos")
        self.verticalLayout_4.addWidget(self.bt_menu_trabajos)
        self.bt_menu_sociales = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_sociales.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_sociales.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_sociales.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/social-network.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_sociales.setIcon(icon9)
        self.bt_menu_sociales.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_sociales.setObjectName("bt_menu_sociales")
        self.verticalLayout_4.addWidget(self.bt_menu_sociales)
        self.bt_menu_paises = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_paises.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_paises.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_paises.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/country-2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_paises.setIcon(icon10)
        self.bt_menu_paises.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_paises.setObjectName("bt_menu_paises")
        self.verticalLayout_4.addWidget(self.bt_menu_paises)
        self.bt_menu_provincias = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_provincias.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_provincias.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_provincias.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/flag-1.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_provincias.setIcon(icon11)
        self.bt_menu_provincias.setIconSize(QtCore.QSize(30, 30))
        self.bt_menu_provincias.setObjectName("bt_menu_provincias")
        self.verticalLayout_4.addWidget(self.bt_menu_provincias)
        self.bt_menu_municipios = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_municipios.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_municipios.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_municipios.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/location.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_municipios.setIcon(icon12)
        self.bt_menu_municipios.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_municipios.setObjectName("bt_menu_municipios")
        self.verticalLayout_4.addWidget(self.bt_menu_municipios)
        self.bt_menu_materiales = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_materiales.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_materiales.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_materiales.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/materials.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_materiales.setIcon(icon13)
        self.bt_menu_materiales.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_materiales.setObjectName("bt_menu_materiales")
        self.verticalLayout_4.addWidget(self.bt_menu_materiales)
        self.bt_menu_tecnicas = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_tecnicas.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_tecnicas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_tecnicas.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/solution.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_tecnicas.setIcon(icon14)
        self.bt_menu_tecnicas.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_tecnicas.setObjectName("bt_menu_tecnicas")
        self.verticalLayout_4.addWidget(self.bt_menu_tecnicas)
        self.bt_menu_tonos = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_tonos.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_tonos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_tonos.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/palette.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_tonos.setIcon(icon15)
        self.bt_menu_tonos.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_tonos.setObjectName("bt_menu_tonos")
        self.verticalLayout_4.addWidget(self.bt_menu_tonos)
        self.bt_menu_pagos = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_menu_pagos.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_menu_pagos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_menu_pagos.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/credit-card.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_pagos.setIcon(icon16)
        self.bt_menu_pagos.setIconSize(QtCore.QSize(35, 35))
        self.bt_menu_pagos.setObjectName("bt_menu_pagos")
        self.verticalLayout_4.addWidget(self.bt_menu_pagos)
        self.bt_stats = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_stats.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_stats.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_stats.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/stats.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_stats.setIcon(icon17)
        self.bt_stats.setIconSize(QtCore.QSize(35, 35))
        self.bt_stats.setObjectName("bt_stats")
        self.verticalLayout_4.addWidget(self.bt_stats)
        self.bt_productos = QtWidgets.QPushButton(parent=self.widget_menu_lateral)
        self.bt_productos.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_productos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_productos.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/products.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_productos.setIcon(icon18)
        self.bt_productos.setIconSize(QtCore.QSize(35, 35))
        self.bt_productos.setObjectName("bt_productos")
        self.verticalLayout_4.addWidget(self.bt_productos)
        self.scrollArea.setWidget(self.widget_menu_lateral)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.frame_control)
        self.frame_paginas = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_paginas.setStyleSheet("")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_paginas)
        self.stackedWidget.setStyleSheet("QLabel{\n"
"font-family:\"Oswald\";\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(180, 180, 180);\n"
"    border: 3px solid   rgb(50, 50, 50);\n"
"    padding: 5px;\n"
"    border-radius:10px;\n"
"font-family:\"Oswald\";\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(244, 240, 240);\n"
"    \n"
"}\n"
"\n"
" QLineEdit {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-family: \"Oswald\";\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border: 2px solid rgb(255, 140, 0);\n"
"    }\n"
"QComboBox {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-family: \"Oswald\";\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QComboBox::drop-down {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 20px;\n"
"        border-left-width: 0px;\n"
"        border-top-right-radius: 10px;\n"
"        border-bottom-right-radius: 10px;\n"
"        background-color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"    QComboBox::down-arrow {\n"
"        image: url(\"views/images/dropdownbtn.png\");\n"
"        width: 20px;\n"
"        height: 20px;\n"
"    }\n"
"\n"
"   QComboBox:focus {\n"
"        border: 2px solid rgb(255, 255, 255);\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView {\n"
"        background-color: rgb(21, 128, 194);\n"
"        color: white;\n"
"        selection-background-color: rgb(255, 255, 255);\n"
"        selection-color: black;\n"
"    }\n"
"QTextEdit {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"    QTextEdit:focus {\n"
"         border: 2px solid rgb(255, 140, 0);\n"
"    }")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_stats = QtWidgets.QWidget()
        self.page_stats.setObjectName("page_stats")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_stats)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.bt_stats_day = QtWidgets.QPushButton(parent=self.page_stats)
        self.bt_stats_day.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_stats_day.setObjectName("bt_stats_day")
        self.verticalLayout_10.addWidget(self.bt_stats_day)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.bt_stats_rango = QtWidgets.QPushButton(parent=self.page_stats)
        self.bt_stats_rango.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_stats_rango.setObjectName("bt_stats_rango")
        self.verticalLayout_10.addWidget(self.bt_stats_rango)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_20.addLayout(self.verticalLayout_10)
        self.bt_stats_productos = QtWidgets.QPushButton(parent=self.page_stats)
        self.bt_stats_productos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_stats_productos.setObjectName("bt_stats_productos")
        self.horizontalLayout_20.addWidget(self.bt_stats_productos)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.stackedWidget.addWidget(self.page_stats)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_paginas)
        self.verticalLayout_2.addWidget(self.frame_contenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        OnInkMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OnInkMainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.bt_close.clicked.connect(OnInkMainWindow.close) # type: ignore
        self.bt_maximizar.clicked.connect(OnInkMainWindow.showMaximized) # type: ignore
        self.bt_maximizar.clicked.connect(self.bt_restaurar.show) # type: ignore
        self.bt_maximizar.clicked.connect(self.bt_maximizar.hide) # type: ignore
        self.bt_minimizar.clicked.connect(OnInkMainWindow.showMinimized) # type: ignore
        self.bt_restaurar.clicked.connect(self.bt_maximizar.show) # type: ignore
        self.bt_restaurar.clicked.connect(self.bt_restaurar.hide) # type: ignore
        self.bt_restaurar.clicked.connect(OnInkMainWindow.showNormal) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OnInkMainWindow)

    def retranslateUi(self, OnInkMainWindow):
        _translate = QtCore.QCoreApplication.translate
        OnInkMainWindow.setWindowTitle(_translate("OnInkMainWindow", "MainWindow"))
        self.bt_menu.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#040404;\">Mostrar/Ocultar menú</span></p></body></html>"))
        self.label.setText(_translate("OnInkMainWindow", "OnInk"))
        self.bt_minimizar.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Minimizar</span></p></body></html>"))
        self.bt_restaurar.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Normal</span></p></body></html>"))
        self.bt_maximizar.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Maximizar</span></p></body></html>"))
        self.bt_close.setToolTip(_translate("OnInkMainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Cerrar</span></p></body></html>"))
        self.label_2.setText(_translate("OnInkMainWindow", "Menú de opciones"))
        self.bt_menu_home.setText(_translate("OnInkMainWindow", "Inicio"))
        self.bt_menu_clientes.setText(_translate("OnInkMainWindow", "Clientes"))
        self.bt_menu_trabajos.setText(_translate("OnInkMainWindow", "Trabajos "))
        self.bt_menu_sociales.setText(_translate("OnInkMainWindow", "Redes "))
        self.bt_menu_paises.setText(_translate("OnInkMainWindow", "Países "))
        self.bt_menu_provincias.setText(_translate("OnInkMainWindow", "Provincias "))
        self.bt_menu_municipios.setText(_translate("OnInkMainWindow", "Municipios "))
        self.bt_menu_materiales.setText(_translate("OnInkMainWindow", "Materiales "))
        self.bt_menu_tecnicas.setText(_translate("OnInkMainWindow", "Técnicas "))
        self.bt_menu_tonos.setText(_translate("OnInkMainWindow", "Tonos "))
        self.bt_menu_pagos.setText(_translate("OnInkMainWindow", "Pagos "))
        self.bt_stats.setText(_translate("OnInkMainWindow", "Estadísticas"))
        self.bt_productos.setText(_translate("OnInkMainWindow", "Productos"))
        self.bt_stats_day.setText(_translate("OnInkMainWindow", "Trabajos por día"))
        self.bt_stats_rango.setText(_translate("OnInkMainWindow", "Trabajos por rango"))
        self.bt_stats_productos.setText(_translate("OnInkMainWindow", "Relacion de productos por día"))
