# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\views\municipios.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MunicipiosIndex(object):
    def setupUi(self, MunicipiosIndex):
        MunicipiosIndex.setObjectName("MunicipiosIndex")
        MunicipiosIndex.resize(687, 467)
        self.verticalLayout = QtWidgets.QVBoxLayout(MunicipiosIndex)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=MunicipiosIndex)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_create = QtWidgets.QPushButton(parent=MunicipiosIndex)
        self.bt_create.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/icons8-plus-24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_create.setIcon(icon)
        self.bt_create.setIconSize(QtCore.QSize(32, 32))
        self.bt_create.setObjectName("bt_create")
        self.horizontalLayout.addWidget(self.bt_create)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=MunicipiosIndex)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_search = QtWidgets.QLineEdit(parent=MunicipiosIndex)
        self.le_search.setText("")
        self.le_search.setObjectName("le_search")
        self.horizontalLayout_2.addWidget(self.le_search)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(parent=MunicipiosIndex)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cb_provincia = QtWidgets.QComboBox(parent=MunicipiosIndex)
        self.cb_provincia.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_provincia.setObjectName("cb_provincia")
        self.horizontalLayout_2.addWidget(self.cb_provincia)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.bt_refresh = QtWidgets.QPushButton(parent=MunicipiosIndex)
        self.bt_refresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/refresh.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_refresh.setIcon(icon1)
        self.bt_refresh.setIconSize(QtCore.QSize(32, 32))
        self.bt_refresh.setObjectName("bt_refresh")
        self.horizontalLayout_2.addWidget(self.bt_refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layout_tabla = QtWidgets.QHBoxLayout()
        self.layout_tabla.setObjectName("layout_tabla")
        self.verticalLayout.addLayout(self.layout_tabla)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 6)

        self.retranslateUi(MunicipiosIndex)
        QtCore.QMetaObject.connectSlotsByName(MunicipiosIndex)

    def retranslateUi(self, MunicipiosIndex):
        _translate = QtCore.QCoreApplication.translate
        MunicipiosIndex.setWindowTitle(_translate("MunicipiosIndex", "Form"))
        self.label.setText(_translate("MunicipiosIndex", "Municipios"))
        self.bt_create.setText(_translate("MunicipiosIndex", "Nuevo"))
        self.label_2.setText(_translate("MunicipiosIndex", "Buscar:"))
        self.le_search.setPlaceholderText(_translate("MunicipiosIndex", "Buscar..."))
        self.label_3.setText(_translate("MunicipiosIndex", "Provincia: "))
        self.cb_provincia.setPlaceholderText(_translate("MunicipiosIndex", "Provincia"))
        self.bt_refresh.setText(_translate("MunicipiosIndex", "Reestablecer"))
