# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\views\paises.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaisWidget(object):
    def setupUi(self, PaisWidget):
        PaisWidget.setObjectName("PaisWidget")
        PaisWidget.resize(604, 459)
        self.verticalLayout = QtWidgets.QVBoxLayout(PaisWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=PaisWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutFiltro = QtWidgets.QHBoxLayout()
        self.layoutFiltro.setObjectName("layoutFiltro")
        self.label_2 = QtWidgets.QLabel(parent=PaisWidget)
        self.label_2.setObjectName("label_2")
        self.layoutFiltro.addWidget(self.label_2)
        self.le_search_pais = QtWidgets.QLineEdit(parent=PaisWidget)
        self.le_search_pais.setObjectName("le_search_pais")
        self.layoutFiltro.addWidget(self.le_search_pais)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutFiltro.addItem(spacerItem)
        self.bt_add_pais = QtWidgets.QPushButton(parent=PaisWidget)
        self.bt_add_pais.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/icons8-plus-24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_add_pais.setIcon(icon)
        self.bt_add_pais.setIconSize(QtCore.QSize(32, 32))
        self.bt_add_pais.setObjectName("bt_add_pais")
        self.layoutFiltro.addWidget(self.bt_add_pais)
        self.verticalLayout.addLayout(self.layoutFiltro)
        self.layoutTablaPaises = QtWidgets.QHBoxLayout()
        self.layoutTablaPaises.setObjectName("layoutTablaPaises")
        self.verticalLayout.addLayout(self.layoutTablaPaises)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 7)

        self.retranslateUi(PaisWidget)
        QtCore.QMetaObject.connectSlotsByName(PaisWidget)

    def retranslateUi(self, PaisWidget):
        _translate = QtCore.QCoreApplication.translate
        PaisWidget.setWindowTitle(_translate("PaisWidget", "Form"))
        self.label.setText(_translate("PaisWidget", "Países"))
        self.label_2.setText(_translate("PaisWidget", "Buscar: "))
        self.le_search_pais.setPlaceholderText(_translate("PaisWidget", "Buscar..."))
        self.bt_add_pais.setText(_translate("PaisWidget", "Agregar nuevo"))
