# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\views\provincias.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


