# Form implementation generated from reading ui file 'd:\python\OnInk\onink\views\showClientView.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_showClient(object):
    def setupUi(self, showClient):
        showClient.setObjectName("showClient")
        showClient.resize(673, 629)
        showClient.setStyleSheet("")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(showClient)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bt_volver_show = QtWidgets.QPushButton(parent=showClient)
        self.bt_volver_show.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\python\\OnInk\\onink\\views\\images/back-arrow.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_volver_show.setIcon(icon)
        self.bt_volver_show.setIconSize(QtCore.QSize(32, 32))
        self.bt_volver_show.setObjectName("bt_volver_show")
        self.horizontalLayout_5.addWidget(self.bt_volver_show)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=showClient)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.scrollArea = QtWidgets.QScrollArea(parent=showClient)
        self.scrollArea.setStyleSheet("QLineEdit{\n"
"background-color: rgb(70, 90, 110);\n"
"}\n"
"QWidget{\n"
"background-color: rgb(44, 62, 80);\n"
"}\n"
"QScrollArea {\n"
"        border-radius: 5px;\n"
"        margin: 5px;\n"
"    }\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: rgb(235, 235, 235);\n"
"        width: 10px;\n"
"        margin: 0px 0 0px 0;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"    background-color: rgb(243, 156, 18);\n"
"        min-height: 20px;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical {\n"
"        background-color: #F5F5F5;\n"
"        height: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"        border-top-left-radius: 5px;\n"
"        border-top-right-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical {\n"
"        background-color: #F5F5F5;\n"
"        height: 0px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"        border-bottom-left-radius: 5px;\n"
"        border-bottom-right-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background-color: none;\n"
"    }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 645, 553))
        self.scrollAreaWidgetContents.setStyleSheet(" QLineEdit {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-family: \"Oswald\";\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border: 2px solid rgb(255, 140, 0);\n"
"    }\n"
"QTextEdit {\n"
"        background-color: rgb(70, 90, 110);\n"
"        color: white;\n"
"        border: 2px solid white;\n"
"        border-radius: 10px;\n"
"        font-size: 12pt;\n"
"        padding: 5px;\n"
"    }\n"
"    QTextEdit:focus {\n"
"         border: 2px solid rgb(255, 140, 0);\n"
"    }")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.personalLayout = QtWidgets.QVBoxLayout()
        self.personalLayout.setObjectName("personalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lb_pic_client_show_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.lb_pic_client_show_2.setMinimumSize(QtCore.QSize(230, 230))
        self.lb_pic_client_show_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lb_pic_client_show_2.setStyleSheet("border: 3px solid white")
        self.lb_pic_client_show_2.setText("")
        self.lb_pic_client_show_2.setScaledContents(True)
        self.lb_pic_client_show_2.setObjectName("lb_pic_client_show_2")
        self.horizontalLayout_14.addWidget(self.lb_pic_client_show_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.le_ci_show_2 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.le_ci_show_2.setReadOnly(True)
        self.le_ci_show_2.setObjectName("le_ci_show_2")
        self.horizontalLayout_16.addWidget(self.le_ci_show_2)
        self.horizontalLayout_16.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.le_phone_show_2 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.le_phone_show_2.setReadOnly(True)
        self.le_phone_show_2.setObjectName("le_phone_show_2")
        self.horizontalLayout_17.addWidget(self.le_phone_show_2)
        self.horizontalLayout_17.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_13 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_18.addWidget(self.label_13)
        self.le_pais_show_2 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.le_pais_show_2.setReadOnly(True)
        self.le_pais_show_2.setObjectName("le_pais_show_2")
        self.horizontalLayout_18.addWidget(self.le_pais_show_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.le_provincia_show_2 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.le_provincia_show_2.setReadOnly(True)
        self.le_provincia_show_2.setObjectName("le_provincia_show_2")
        self.horizontalLayout_19.addWidget(self.le_provincia_show_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.le_municipio_show_2 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.le_municipio_show_2.setReadOnly(True)
        self.le_municipio_show_2.setObjectName("le_municipio_show_2")
        self.horizontalLayout_20.addWidget(self.le_municipio_show_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.personalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.le_full_name_show_2 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.le_full_name_show_2.setReadOnly(True)
        self.le_full_name_show_2.setObjectName("le_full_name_show_2")
        self.horizontalLayout_9.addWidget(self.le_full_name_show_2)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 8)
        self.personalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_16 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_22.addWidget(self.label_16)
        self.txted_notas_show_2 = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.txted_notas_show_2.setReadOnly(True)
        self.txted_notas_show_2.setObjectName("txted_notas_show_2")
        self.horizontalLayout_22.addWidget(self.txted_notas_show_2)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 8)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.txted_alcance_show_2 = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.txted_alcance_show_2.setReadOnly(True)
        self.txted_alcance_show_2.setObjectName("txted_alcance_show_2")
        self.horizontalLayout_23.addWidget(self.txted_alcance_show_2)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 8)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_23)
        self.personalLayout.addLayout(self.horizontalLayout_21)
        self.verticalLayout.addLayout(self.personalLayout)
        self.line = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.layoutUsernames = QtWidgets.QVBoxLayout()
        self.layoutUsernames.setObjectName("layoutUsernames")
        self.verticalLayout.addLayout(self.layoutUsernames)
        self.line_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.layoutWorks = QtWidgets.QVBoxLayout()
        self.layoutWorks.setObjectName("layoutWorks")
        self.label_19 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.layoutWorks.addWidget(self.label_19)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_18 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_24.addWidget(self.label_18)
        self.gasto_total = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.gasto_total.setReadOnly(True)
        self.gasto_total.setObjectName("gasto_total")
        self.horizontalLayout_24.addWidget(self.gasto_total)
        self.layoutWorks.addLayout(self.horizontalLayout_24)
        self.verticalLayout.addLayout(self.layoutWorks)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)

        self.retranslateUi(showClient)
        QtCore.QMetaObject.connectSlotsByName(showClient)

    def retranslateUi(self, showClient):
        _translate = QtCore.QCoreApplication.translate
        showClient.setWindowTitle(_translate("showClient", "Form"))
        self.bt_volver_show.setText(_translate("showClient", "Volver"))
        self.label_3.setText(_translate("showClient", "Datos del cliente"))
        self.label_11.setText(_translate("showClient", "CI: "))
        self.label_12.setText(_translate("showClient", "Teléfono: "))
        self.label_13.setText(_translate("showClient", "País:"))
        self.label_14.setText(_translate("showClient", "Provincia: "))
        self.label_15.setText(_translate("showClient", "Municipio: "))
        self.label_10.setText(_translate("showClient", "Nombre y apellidos: "))
        self.label_16.setText(_translate("showClient", "Notas: "))
        self.txted_notas_show_2.setPlaceholderText(_translate("showClient", "Sin notas"))
        self.label_17.setText(_translate("showClient", "Vía de llegada: "))
        self.txted_alcance_show_2.setPlaceholderText(_translate("showClient", "Sin información de como llegó hasta nosotros"))
        self.label_19.setText(_translate("showClient", "Resumen de trabajos"))
        self.label_18.setText(_translate("showClient", "Gasto total: "))
