# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\views\socials.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SocialsIndex(object):
    def setupUi(self, SocialsIndex):
        SocialsIndex.setObjectName("SocialsIndex")
        SocialsIndex.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SocialsIndex)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=SocialsIndex)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=SocialsIndex)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_search = QtWidgets.QLineEdit(parent=SocialsIndex)
        self.le_search.setText("")
        self.le_search.setObjectName("le_search")
        self.horizontalLayout_2.addWidget(self.le_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bt_create = QtWidgets.QPushButton(parent=SocialsIndex)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/icons8-plus-24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_create.setIcon(icon)
        self.bt_create.setIconSize(QtCore.QSize(32, 32))
        self.bt_create.setObjectName("bt_create")
        self.horizontalLayout_2.addWidget(self.bt_create)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layout_tabla = QtWidgets.QHBoxLayout()
        self.layout_tabla.setObjectName("layout_tabla")
        self.verticalLayout.addLayout(self.layout_tabla)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 6)

        self.retranslateUi(SocialsIndex)
        QtCore.QMetaObject.connectSlotsByName(SocialsIndex)

    def retranslateUi(self, SocialsIndex):
        _translate = QtCore.QCoreApplication.translate
        SocialsIndex.setWindowTitle(_translate("SocialsIndex", "Form"))
        self.label.setText(_translate("SocialsIndex", "Redes Sociales"))
        self.label_2.setText(_translate("SocialsIndex", "Buscar:"))
        self.le_search.setPlaceholderText(_translate("SocialsIndex", "Buscar..."))
        self.bt_create.setText(_translate("SocialsIndex", "Nuevo"))
