# Form implementation generated from reading ui file 'd:\Programacion\Proyectos\Python\OnInk\onink\views\trabajosIndex.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_trabajosIndex(object):
    def setupUi(self, trabajosIndex):
        trabajosIndex.setObjectName("trabajosIndex")
        trabajosIndex.resize(620, 521)
        trabajosIndex.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(trabajosIndex)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=trabajosIndex)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_create = QtWidgets.QPushButton(parent=trabajosIndex)
        self.bt_create.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/icons8-plus-24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_create.setIcon(icon)
        self.bt_create.setIconSize(QtCore.QSize(32, 32))
        self.bt_create.setObjectName("bt_create")
        self.horizontalLayout.addWidget(self.bt_create)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutFiltro = QtWidgets.QHBoxLayout()
        self.layoutFiltro.setObjectName("layoutFiltro")
        self.label_2 = QtWidgets.QLabel(parent=trabajosIndex)
        self.label_2.setObjectName("label_2")
        self.layoutFiltro.addWidget(self.label_2)
        self.le_search = QtWidgets.QLineEdit(parent=trabajosIndex)
        self.le_search.setObjectName("le_search")
        self.layoutFiltro.addWidget(self.le_search)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutFiltro.addItem(spacerItem2)
        self.bt_tipos = QtWidgets.QPushButton(parent=trabajosIndex)
        self.bt_tipos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_tipos.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Programacion\\Proyectos\\Python\\OnInk\\onink\\views\\images/folder-won.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_tipos.setIcon(icon1)
        self.bt_tipos.setIconSize(QtCore.QSize(35, 35))
        self.bt_tipos.setObjectName("bt_tipos")
        self.layoutFiltro.addWidget(self.bt_tipos)
        self.verticalLayout.addLayout(self.layoutFiltro)
        self.filterDatesLayout = QtWidgets.QHBoxLayout()
        self.filterDatesLayout.setObjectName("filterDatesLayout")
        self.verticalLayout.addLayout(self.filterDatesLayout)
        self.layout_tabla = QtWidgets.QHBoxLayout()
        self.layout_tabla.setObjectName("layout_tabla")
        self.verticalLayout.addLayout(self.layout_tabla)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 9)

        self.retranslateUi(trabajosIndex)
        QtCore.QMetaObject.connectSlotsByName(trabajosIndex)

    def retranslateUi(self, trabajosIndex):
        _translate = QtCore.QCoreApplication.translate
        trabajosIndex.setWindowTitle(_translate("trabajosIndex", "Form"))
        self.label.setText(_translate("trabajosIndex", "Trabajos"))
        self.bt_create.setText(_translate("trabajosIndex", "Agregar nuevo"))
        self.label_2.setText(_translate("trabajosIndex", "Buscar: "))
        self.le_search.setPlaceholderText(_translate("trabajosIndex", "Buscar..."))
        self.bt_tipos.setText(_translate("trabajosIndex", "Tipos de trabajos"))
